
import React, { useState, useEffect, useRef } from 'react';
import { 
  Monitor, Layout, Layers, ToggleLeft, ToggleRight, 
  AlertTriangle, Megaphone, Power, CheckCircle, Smartphone, Database, Server, HardDrive, Copy, Check, Save, RefreshCw, Key,
  Globe, MapPin, Phone, Mail, Upload, X, Image as ImageIcon,
  Zap, PlusCircle, RotateCcw, Wifi, WifiOff, Globe2, Lock, ShieldCheck, Terminal, AlertCircle, Info, Code, ArrowRight
} from 'lucide-react';
import { Button } from '../../ui/Button';
import { useSiteConfig, ToggableModule, LandingSection } from '../../../contexts/SiteConfigContext';
import { isSupabaseConfigured, isGlobalConfig, supabase } from '../../../services/supabaseClient';
import { AppModule } from '../../../types';

const SCHEMA_SQL = `-- ১. টেবিলগুলো তৈরি বা আপডেট করার জন্য নিচের কোডটি রান করুন

-- ব্লগ রিকোয়েস্ট টেবিল (নিশ্চিত করা হচ্ছে সব কলাম আছে কি না)
create table if not exists public.blog_requests (
  id bigint generated by default as identity primary key, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- মিসিং কলামগুলো যোগ করা হচ্ছে (যদি আগে না থাকে)
alter table public.blog_requests add column if not exists title text;
alter table public.blog_requests add column if not exists category text;
alter table public.blog_requests add column if not exists content text;
alter table public.blog_requests add column if not exists author text;
alter table public.blog_requests add column if not exists posteddate text;
alter table public.blog_requests add column if not exists date text;
alter table public.blog_requests add column if not exists image text;
alter table public.blog_requests add column if not exists readtime text;
alter table public.blog_requests add column if not exists excerpt text;
alter table public.blog_requests add column if not exists status text default 'Pending';

-- জব রিকোয়েস্ট টেবিল আপডেট
create table if not exists public.requests (
  id bigint generated by default as identity primary key, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.requests add column if not exists title text;
alter table public.requests add column if not exists company text;
alter table public.requests add column if not exists description text;
alter table public.requests add column if not exists location text;
alter table public.requests add column if not exists salary text;
alter table public.requests add column if not exists type text;
alter table public.requests add column if not exists deadline text;
alter table public.requests add column if not exists postedby text;
alter table public.requests add column if not exists category text;
alter table public.requests add column if not exists status text default 'Pending';
alter table public.requests add column if not exists posteddate text;

-- মেইন জব এবং ব্লগ টেবিল আপডেট (Approved Content)
create table if not exists public.jobs (id bigint generated by default as identity primary key);
alter table public.jobs add column if not exists title text;
alter table public.jobs add column if not exists company text;
alter table public.jobs add column if not exists posteddate text;
alter table public.jobs add column if not exists status text default 'Active';

create table if not exists public.blogs (id bigint generated by default as identity primary key);
alter table public.blogs add column if not exists title text;
alter table public.blogs add column if not exists category text;
alter table public.blogs add column if not exists posteddate text;
alter table public.blogs add column if not exists date text;
alter table public.blogs add column if not exists status text default 'Active';

-- ২. সিকিউরিটি পলিসি (RLS)
alter table public.blog_requests enable row level security;
do $$ begin
  create policy "Public Access" on public.blog_requests for all using (true) with check (true);
exception when others then null; end $$;

alter table public.requests enable row level security;
do $$ begin
  create policy "Public Access" on public.requests for all using (true) with check (true);
exception when others then null; end $$;

alter table public.jobs enable row level security;
do $$ begin
  create policy "Public Access" on public.jobs for all using (true) with check (true);
exception when others then null; end $$;

alter table public.blogs enable row level security;
do $$ begin
  create policy "Public Access" on public.blogs for all using (true) with check (true);
exception when others then null; end $$;

-- পারমিশন গ্রান্ট
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
`;

interface ToggleSwitchProps {
  label: string;
  checked: boolean;
  onChange: () => void;
  color?: string;
}

const ToggleSwitch: React.FC<ToggleSwitchProps> = ({ label, checked, onChange, color = 'bg-green-500' }) => (
  <div className="flex items-center justify-between p-4 bg-white rounded-xl border border-gray-100 hover:border-gray-200 shadow-sm transition-all">
    <span className="font-semibold text-gray-800">{label}</span>
    <button 
      onClick={onChange} 
      className={`relative w-12 h-6 rounded-full transition-colors duration-300 ${checked ? color : 'bg-gray-200'}`}
    >
      <div className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full shadow-sm transform transition-transform duration-300 ${checked ? 'translate-x-6' : 'translate-x-0'}`}></div>
    </button>
  </div>
);

export const AdminWebsiteManage = () => {
  const { modules, sections, settings, toggleModule, toggleSection, updateSettings } = useSiteConfig();
  const [copied, setCopied] = useState(false);
  const [configCopied, setConfigCopied] = useState(false);
  const logoInputRef = useRef<HTMLInputElement>(null);

  const [dbUrl, setDbUrl] = useState(localStorage.getItem('dream_sb_url') || '');
  const [dbKey, setDbKey] = useState(localStorage.getItem('dream_sb_key') || '');
  const [isSaving, setIsSaving] = useState(false);
  const [testResult, setTestResult] = useState<string | null>(null);
  const [statusColor, setStatusColor] = useState('gray');
  const [showGlobalInstructions, setShowGlobalInstructions] = useState(true);
  const [isUploadingLogo, setIsUploadingLogo] = useState(false);

  useEffect(() => {
      if (isSupabaseConfigured) {
          handleTestConnection(true);
      }
  }, []);

  const handleCopySQL = () => {
    navigator.clipboard.writeText(SCHEMA_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyConfig = () => {
    const code = `const HARDCODED_URL = '${dbUrl}';\nconst HARDCODED_KEY = '${dbKey}';`;
    navigator.clipboard.writeText(code);
    setConfigCopied(true);
    setTimeout(() => setConfigCopied(false), 2000);
  };

  const handleSaveDbConfig = () => {
    setIsSaving(true);
    let finalUrl = dbUrl.trim();
    if (finalUrl && !finalUrl.startsWith('http')) finalUrl = 'https://' + finalUrl;
    if (finalUrl.endsWith('/')) finalUrl = finalUrl.slice(0, -1);
    localStorage.setItem('dream_sb_url', finalUrl);
    localStorage.setItem('dream_sb_key', dbKey.trim());
    setTimeout(() => { setIsSaving(false); window.location.reload(); }, 1000);
  };

  const handleTestConnection = async (silent = false) => {
      if(!silent) setTestResult('Testing Connection...');
      try {
          const { count, error } = await supabase.from('requests').select('*', { count: 'exact', head: true });
          if (error) { setTestResult(`Connection Failed: ${error.message}`); setStatusColor('red'); }
          else { setTestResult(`✅ Connected! Found ${count} pending requests.`); setStatusColor('green'); }
      } catch (err: any) { setTestResult(`Error: ${err.message}`); setStatusColor('red'); }
  };

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setIsUploadingLogo(true);
      const reader = new FileReader();
      reader.onloadend = () => {
        updateSettings('websiteLogo', reader.result as string);
        setIsUploadingLogo(false);
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <div className="space-y-8 animate-fade-in max-w-5xl mx-auto">
      <div className={`relative overflow-hidden rounded-2xl p-1 shadow-md ${isGlobalConfig ? 'bg-gradient-to-r from-emerald-400 to-cyan-500' : 'bg-gradient-to-r from-amber-400 to-orange-50'}`}>
        <div className="bg-white/95 backdrop-blur-md rounded-xl p-6 md:p-8">
          <div className="flex flex-col lg:flex-row items-center lg:items-start justify-between gap-8">
            <div className="flex items-start gap-6">
              <div className={`p-5 rounded-2xl shadow-xl shrink-0 ${isGlobalConfig ? 'bg-emerald-500 text-white' : 'bg-amber-500 text-white'}`}>{isGlobalConfig ? <Globe2 size={40} /> : <Lock size={40} />}</div>
              <div className="text-center lg:text-left">
                <h2 className={`text-3xl font-black tracking-tight ${isGlobalConfig ? 'text-emerald-900' : 'text-amber-900'}`}>{isGlobalConfig ? 'GLOBAL SYSTEM ONLINE' : 'LOCAL MODE (RESTRICTED)'}</h2>
                <p className={`mt-2 font-medium text-lg max-w-lg ${isGlobalConfig ? 'text-emerald-700' : 'text-amber-800'}`}>{isGlobalConfig ? 'Success! Real-time syncing is active.' : 'Connected locally only.'}</p>
                <div className="mt-6 flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                  <Button onClick={() => setShowGlobalInstructions(!showGlobalInstructions)} className="bg-amber-600 hover:bg-amber-700 text-white border-none shadow-lg font-bold px-6 py-3 rounded-xl flex items-center gap-2 transition-all"><Globe2 size={18} /> {showGlobalInstructions ? 'Hide Code' : 'View Global Config'}</Button>
                </div>
              </div>
            </div>
            {isSupabaseConfigured && (
              <div className="flex flex-col gap-3 w-full lg:w-auto">
                <div className="bg-gray-50 rounded-xl p-4 border border-gray-200 flex items-center justify-between gap-4 shadow-inner">
                   <div className="flex items-center gap-2 text-sm font-bold text-gray-700"><div className={`w-3 h-3 rounded-full ${statusColor === 'green' ? 'bg-green-500 animate-pulse' : statusColor === 'red' ? 'bg-red-500' : 'bg-gray-400'}`}></div>Status</div>
                   <span className={`text-xs font-bold px-2 py-1 rounded uppercase ${statusColor === 'green' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}> {statusColor === 'green' ? 'Connected' : 'Error'} </span>
                </div>
                <Button onClick={() => handleTestConnection(false)} variant="outline" className="w-full justify-center bg-white hover:bg-gray-50 text-gray-700 border-gray-300 font-bold"><Zap size={16} className="mr-2 text-yellow-500"/> Test Connection</Button>
              </div>
            )}
          </div>
          {showGlobalInstructions && (
            <div className="mt-8 bg-slate-900 rounded-2xl p-6 border border-slate-700 text-white animate-fade-in relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500 rounded-full blur-[60px] opacity-20"></div>
                <div className="relative z-10">
                    <div className="flex justify-between items-center mb-4"><h3 className="text-xl font-bold flex items-center gap-2"><Code size={24} className="text-emerald-400" /> Setup Global Database</h3><button onClick={() => setShowGlobalInstructions(false)} className="bg-slate-800 p-2 rounded-full hover:bg-slate-700"><X size={20}/></button></div>
                    <div className="bg-black/50 rounded-xl border border-slate-700 p-4 mb-4 relative group">
                        <pre className="font-mono text-xs sm:text-sm text-emerald-400 overflow-x-auto whitespace-pre-wrap break-all">{`const HARDCODED_URL = '${dbUrl || 'YOUR_PROJECT_URL'}';\nconst HARDCODED_KEY = '${dbKey || 'YOUR_ANON_KEY'}';`}</pre>
                        <button onClick={handleCopyConfig} className="absolute top-2 right-2 bg-white text-slate-900 px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 hover:bg-emerald-50 transition-colors shadow-lg">{configCopied ? <Check size={14}/> : <Copy size={14}/>} {configCopied ? 'Copied' : 'Copy'}</button>
                    </div>
                </div>
            </div>
          )}
        </div>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
         <div className="px-8 py-6 border-b border-gray-100 flex flex-col md:flex-row justify-between items-center gap-4 bg-gradient-to-r from-gray-50 to-white">
            <div className="flex items-center gap-3"><div className="p-2 bg-blue-50 text-blue-600 rounded-lg"><Database size={24} /></div><div><h3 className="text-xl font-bold text-gray-900">Database & SQL</h3><p className="text-xs text-gray-500">Run this SQL in your Supabase Editor</p></div></div>
         </div>
         <div className="p-8">
            {!isSupabaseConfigured ? (
                <div className="max-w-2xl mx-auto space-y-6">
                    <input type="text" value={dbUrl} onChange={(e) => setDbUrl(e.target.value)} placeholder="Supabase Project URL" className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none" />
                    <input type="password" value={dbKey} onChange={(e) => setDbKey(e.target.value)} placeholder="Supabase Anon Key" className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none" />
                    <button onClick={handleSaveDbConfig} className="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-lg">Save & Connect</button>
                </div>
            ) : (
                <div className="bg-slate-900 text-slate-300 rounded-2xl overflow-hidden border border-slate-800 shadow-2xl">
                    <div className="bg-slate-950 px-6 py-4 flex justify-between items-center border-b border-slate-800">
                        <div className="flex items-center gap-3"><Server size={18} className="text-emerald-400" /><span className="font-bold text-slate-100">SQL Schema (Required)</span></div>
                        <button onClick={handleCopySQL} className="flex items-center gap-2 text-xs font-bold bg-slate-800 hover:bg-slate-700 text-white px-3 py-1.5 rounded-lg border border-slate-700">{copied ? <Check size={14} className="text-green-400"/> : <Copy size={14} />} {copied ? 'Copied!' : 'Copy Code'}</button>
                    </div>
                    <div className="p-6"><div className="bg-black/50 p-4 rounded-xl font-mono text-xs text-emerald-400 h-64 overflow-y-auto border border-slate-800 custom-scrollbar">{SCHEMA_SQL}</div></div>
                </div>
            )}
         </div>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="p-6 border-b border-gray-100 flex items-center gap-3 bg-gray-50">
          <div className="p-2 bg-blue-100 text-blue-700 rounded-lg"><Globe size={20} /></div>
          <div><h3 className="text-lg font-bold text-gray-900">Branding & Info</h3><p className="text-xs text-gray-500">Website title, logo, and contact</p></div>
        </div>
        <div className="p-6 grid grid-cols-1 lg:grid-cols-3 gap-8">
           <div className="col-span-1">
              <label className="block text-sm font-bold text-gray-700 mb-3">Website Logo</label>
              <div className="border-2 border-dashed border-gray-300 rounded-xl p-6 flex flex-col items-center justify-center min-h-[200px] cursor-pointer hover:bg-gray-50 transition-colors relative group" onClick={() => logoInputRef.current?.click()}>
                 <input type="file" accept="image/*" className="hidden" ref={logoInputRef} onChange={handleLogoUpload} />
                 {isUploadingLogo ? <RefreshCw className="animate-spin text-blue-600" /> : settings.websiteLogo ? <div className="relative w-full h-full flex flex-col items-center"><img src={settings.websiteLogo} alt="Logo" className="max-h-32 object-contain" /></div> : <div className="text-center"><ImageIcon size={24} className="text-gray-400 mx-auto mb-2" /><p className="text-sm font-bold text-gray-600">Upload Logo</p></div>}
              </div>
           </div>
           <div className="col-span-1 lg:col-span-2 space-y-5">
              <div><label className="block text-sm font-bold text-gray-700 mb-2">Website Title</label><input type="text" value={settings.websiteTitle} onChange={(e) => updateSettings('websiteTitle', e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" /></div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                 <div><label className="block text-sm font-bold text-gray-700 mb-2">Contact Email</label><input type="text" value={settings.contactEmail} onChange={(e) => updateSettings('contactEmail', e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" /></div>
                 <div><label className="block text-sm font-bold text-gray-700 mb-2">Contact Phone</label><input type="text" value={settings.contactPhone} onChange={(e) => updateSettings('contactPhone', e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-xl outline-none focus:ring-2 focus:ring-blue-500" /></div>
              </div>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="p-5 border-b border-gray-100 flex items-center gap-3 bg-gray-50/50"><Layers size={20} className="text-indigo-600"/><h3 className="font-bold text-gray-900">Module Status</h3></div>
          <div className="p-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
             {Object.keys(modules).map((mod) => (
                <ToggleSwitch key={mod} label={mod} checked={modules[mod as ToggableModule]} onChange={() => toggleModule(mod as ToggableModule)} />
             ))}
          </div>
        </div>
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden h-fit">
          <div className="p-5 border-b border-gray-100 flex items-center gap-3 bg-gray-50/50"><Layout size={20} className="text-pink-600"/><h3 className="font-bold text-gray-900">Landing Page</h3></div>
          <div className="p-6 space-y-4">
             {Object.keys(sections).map((sec) => (
                <ToggleSwitch key={sec} label={sec} checked={sections[sec as LandingSection]} onChange={() => toggleSection(sec as LandingSection)} color="bg-pink-500" />
             ))}
          </div>
        </div>
      </div>
    </div>
  );
};
