
import React, { useState, useEffect, useRef } from 'react';
import { 
  Monitor, Layout, Layers, ToggleLeft, ToggleRight, 
  AlertTriangle, Megaphone, Power, CheckCircle, Smartphone, Database, Server, HardDrive, Copy, Check, Save, RefreshCw, Key,
  Globe, MapPin, Phone, Mail, Upload, X, Image as ImageIcon,
  Zap, PlusCircle, RotateCcw, Wifi, WifiOff, Globe2, Lock, ShieldCheck, Terminal, AlertCircle, Info, Code, ArrowRight
} from 'lucide-react';
import { Button } from '../../ui/Button';
import { useSiteConfig, ToggableModule, LandingSection } from '../../../contexts/SiteConfigContext';
import { isSupabaseConfigured, isGlobalConfig, supabase } from '../../../services/supabaseClient';
import { AppModule } from '../../../types';
import { useData } from '../../../contexts/DataContext';

const SCHEMA_SQL = `-- ১. নতুন টেবিল তৈরি বা আপডেট করুন

-- অ্যাপ কনফিগারেশন টেবিল
create table if not exists public.app_config (
  key text primary key,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ৬৪ জেলার টেবিল
create table if not exists public.districts (
  id text primary key,
  nameen text,
  namebn text,
  division text,
  population text,
  area text,
  description text,
  upazilas jsonb default '[]',
  education jsonb default '{"primary": 0, "highSchool": 0, "college": 0, "university": 0}',
  hospitals jsonb default '[]',
  touristspots jsonb default '[]',
  images jsonb default '[]',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- পাইকারি বিজ্ঞাপন রিকোয়েস্ট টেবিল
create table if not exists public.wholesale_requests (
  id bigint generated by default as identity primary key,
  product text,
  quantity text,
  price text,
  location text,
  sellertype text,
  seller text,
  phone text,
  status text default 'Pending',
  posteddate text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- পাইকারি বিজ্ঞাপন মেইন টেবিল (Approved)
create table if not exists public.wholesale_ads (
  id bigint generated by default as identity primary key,
  product text,
  quantity text,
  price text,
  location text,
  sellertype text,
  seller text,
  phone text,
  status text default 'Active',
  posteddate text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- সিকিউরিটি পলিসি (RLS)
alter table public.app_config enable row level security;
alter table public.districts enable row level security;
alter table public.wholesale_requests enable row level security;
alter table public.wholesale_ads enable row level security;

do $$ begin
  create policy "Public Access Config" on public.app_config for all using (true) with check (true);
  create policy "Public Access Districts" on public.districts for all using (true) with check (true);
  create policy "Public Access wholesale_requests" on public.wholesale_requests for all using (true) with check (true);
  create policy "Public Access wholesale_ads" on public.wholesale_ads for all using (true) with check (true);
exception when others then null; end $$;

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
`;

interface ToggleSwitchProps {
  label: string;
  checked: boolean;
  onChange: () => void;
  color?: string;
}

const ToggleSwitch: React.FC<ToggleSwitchProps> = ({ label, checked, onChange, color = 'bg-brand-600' }) => (
  <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl border border-gray-200 hover:border-brand-200 shadow-sm transition-all group">
    <span className="font-bold text-gray-700 text-sm">{label}</span>
    <button 
      onClick={onChange} 
      className={`relative w-12 h-6 rounded-full transition-colors duration-300 ${checked ? color : 'bg-gray-300'}`}
    >
      <div className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full shadow-sm transform transition-transform duration-300 ${checked ? 'translate-x-6' : 'translate-x-0'}`}></div>
    </button>
  </div>
);

export const AdminWebsiteManage = () => {
  const { modules, sections, settings, toggleModule, toggleSection, updateSettings } = useSiteConfig();
  const { seedDistricts } = useData();
  const [copied, setCopied] = useState(false);
  const [configCopied, setConfigCopied] = useState(false);
  const logoInputRef = useRef<HTMLInputElement>(null);
  const faviconInputRef = useRef<HTMLInputElement>(null);

  const [dbUrl, setDbUrl] = useState(localStorage.getItem('dream_sb_url') || '');
  const [dbKey, setDbKey] = useState(localStorage.getItem('dream_sb_key') || '');
  const [isSaving, setIsSaving] = useState(false);
  const [testResult, setTestResult] = useState<string | null>(null);
  const [statusColor, setStatusColor] = useState('gray');
  const [showGlobalInstructions, setShowGlobalInstructions] = useState(false);
  const [isUploadingLogo, setIsUploadingLogo] = useState(false);
  const [isUploadingFavicon, setIsUploadingFavicon] = useState(false);
  const [isSeeding, setIsSeeding] = useState(false);

  useEffect(() => {
      if (isSupabaseConfigured) {
          handleTestConnection(true);
      }
  }, []);

  const handleCopySQL = () => {
    navigator.clipboard.writeText(SCHEMA_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyConfig = () => {
    const code = `const HARDCODED_URL = '${dbUrl}';\nconst HARDCODED_KEY = '${dbKey}';`;
    navigator.clipboard.writeText(code);
    setConfigCopied(true);
    setTimeout(() => setConfigCopied(false), 2000);
  };

  const handleSaveDbConfig = () => {
    setIsSaving(true);
    let finalUrl = dbUrl.trim();
    if (finalUrl && !finalUrl.startsWith('http')) finalUrl = 'https://' + finalUrl;
    if (finalUrl.endsWith('/')) finalUrl = finalUrl.slice(0, -1);
    localStorage.setItem('dream_sb_url', finalUrl);
    localStorage.setItem('dream_sb_key', dbKey.trim());
    setTimeout(() => { setIsSaving(false); window.location.reload(); }, 1000);
  };

  const handleTestConnection = async (silent = false) => {
      if(!silent) setTestResult('Testing Connection...');
      try {
          // Testing with app_config table which should exist after running SQL
          const { error } = await supabase.from('app_config').select('*', { count: 'exact', head: true });
          if (error && error.code !== 'PGRST116') { // PGRST116 means empty table but exists
              setTestResult(`Connection Failed: ${error.message}`); 
              setStatusColor('red'); 
          }
          else { 
              setTestResult(`✅ Connected! Database is live.`); 
              setStatusColor('green'); 
          }
      } catch (err: any) { setTestResult(`Error: ${err.message}`); setStatusColor('red'); }
  };

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setIsUploadingLogo(true);
      const reader = new FileReader();
      reader.onloadend = () => {
        updateSettings('websiteLogo', reader.result as string);
        setIsUploadingLogo(false);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleFaviconUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setIsUploadingFavicon(true);
      const reader = new FileReader();
      reader.onloadend = () => {
        updateSettings('websiteFavicon', reader.result as string);
        setIsUploadingFavicon(false);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSeedData = async () => {
    if (confirm('This will insert real data for 64 districts into your database. Existing district records with same IDs will be updated. Proceed?')) {
      setIsSeeding(true);
      try {
        await seedDistricts();
      } finally {
        setIsSeeding(false);
      }
    }
  };

  return (
    <div className="space-y-8 animate-fade-in max-w-7xl mx-auto pb-20">
      
      {/* 1. Connection Status Banner */}
      <div className={`relative overflow-hidden rounded-2xl p-1 shadow-lg ${isGlobalConfig ? 'bg-gradient-to-r from-emerald-500 to-cyan-500' : 'bg-gradient-to-r from-amber-400 to-orange-500'}`}>
        <div className="bg-white/95 backdrop-blur-md rounded-xl p-6 md:p-8">
          <div className="flex flex-col lg:flex-row items-center lg:items-start justify-between gap-8">
            <div className="flex items-start gap-6">
              <div className={`p-5 rounded-2xl shadow-xl shrink-0 ${isGlobalConfig ? 'bg-emerald-500 text-white' : 'bg-amber-500 text-white'}`}>
                {isGlobalConfig ? <Globe2 size={40} /> : <Lock size={40} />}
              </div>
              <div className="text-center lg:text-left">
                <h2 className={`text-3xl font-black tracking-tight ${isGlobalConfig ? 'text-emerald-900' : 'text-amber-900'}`}>
                  {isGlobalConfig ? 'GLOBAL SYSTEM ONLINE' : 'LOCAL MODE ENABLED'}
                </h2>
                <p className={`mt-2 font-medium text-lg max-w-lg ${isGlobalConfig ? 'text-emerald-700' : 'text-amber-800'}`}>
                  {isGlobalConfig ? 'Success! Your database is connected and syncing globally.' : 'The app is running in restricted mode. Configure Supabase to enable global sync.'}
                </p>
                <div className="mt-6 flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                   <Button onClick={() => setShowGlobalInstructions(!showGlobalInstructions)} variant="outline" className="bg-white border-gray-300 font-bold">
                     {showGlobalInstructions ? 'Hide Instructions' : 'Setup Global Access'}
                   </Button>
                   <Button onClick={() => handleTestConnection(false)} className="bg-brand-600 text-white flex items-center gap-2">
                     <Zap size={18} /> Test Sync
                   </Button>
                   {isSupabaseConfigured && (
                     <Button 
                       onClick={handleSeedData} 
                       disabled={isSeeding}
                       className="bg-indigo-600 hover:bg-indigo-700 text-white flex items-center gap-2"
                     >
                       {isSeeding ? <RefreshCw className="animate-spin" size={18} /> : <Database size={18} />}
                       Seed 64 Districts Data
                     </Button>
                   )}
                </div>
              </div>
            </div>
            {testResult && (
              <div className={`p-4 rounded-xl border font-bold text-sm ${statusColor === 'green' ? 'bg-green-50 text-green-700 border-green-200' : 'bg-red-50 text-red-700 border-red-200'}`}>
                {testResult}
              </div>
            )}
          </div>
          
          {showGlobalInstructions && (
            <div className="mt-8 bg-slate-900 rounded-2xl p-6 border border-slate-700 text-white animate-fade-in">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-xl font-bold flex items-center gap-2"><Code size={24} className="text-emerald-400" /> Supabase Connection</h3>
                  <button onClick={() => setShowGlobalInstructions(false)}><X size={20}/></button>
                </div>
                <div className="bg-black/50 rounded-xl p-4 font-mono text-sm text-emerald-400 overflow-x-auto break-all">
                  {`SUPABASE_URL: ${dbUrl || 'PROJECT_URL'}\nSUPABASE_ANON_KEY: ${dbKey || 'ANON_KEY'}`}
                </div>
                <div className="mt-4 flex gap-2">
                  <button onClick={handleCopyConfig} className="bg-emerald-600 hover:bg-emerald-700 px-4 py-2 rounded text-xs font-bold flex items-center gap-2 transition-all">
                    {configCopied ? <Check size={14}/> : <Copy size={14}/>} {configCopied ? 'Copied' : 'Copy Config Code'}
                  </button>
                </div>
            </div>
          )}
        </div>
      </div>

      {/* 2. Platform Control Center */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Module Management */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="p-6 border-b border-gray-100 bg-gray-50 flex items-center gap-3">
            <Layers className="text-brand-600" />
            <h3 className="text-xl font-bold text-gray-900">Module Management</h3>
          </div>
          <div className="p-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
            {Object.keys(modules).filter(m => m !== 'admin').map((modId) => (
              <ToggleSwitch 
                key={modId}
                label={modId.charAt(0).toUpperCase() + modId.slice(1).replace('_', ' ')}
                checked={modules[modId as ToggableModule]}
                onChange={() => toggleModule(modId as ToggableModule)}
              />
            ))}
          </div>
        </div>

        {/* Landing Page Sections */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="p-6 border-b border-gray-100 bg-gray-50 flex items-center gap-3">
            <Layout className="text-brand-600" />
            <h3 className="text-xl font-bold text-gray-900">Landing Page Sections</h3>
          </div>
          <div className="p-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
            {Object.keys(sections).map((secId) => (
              <ToggleSwitch 
                key={secId}
                label={secId.charAt(0).toUpperCase() + secId.slice(1)}
                checked={sections[secId as LandingSection]}
                onChange={() => toggleSection(secId as LandingSection)}
                color="bg-indigo-600"
              />
            ))}
          </div>
        </div>
      </div>

      {/* 3. Website Identity & Maintenance */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Maintenance & Announcement */}
        <div className="lg:col-span-1 space-y-8">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
            <h3 className="text-lg font-bold text-gray-900 mb-6 flex items-center gap-2">
              <Power className="text-red-500" /> System Controls
            </h3>
            <div className="space-y-4">
              <ToggleSwitch 
                label="Maintenance Mode" 
                checked={settings.maintenanceMode} 
                onChange={() => updateSettings('maintenanceMode', !settings.maintenanceMode)}
                color="bg-red-600"
              />
              <ToggleSwitch 
                label="Global Announcement" 
                checked={settings.announcementActive} 
                onChange={() => updateSettings('announcementActive', !settings.announcementActive)}
              />
            </div>
            
            {settings.announcementActive && (
              <div className="mt-6 animate-fade-in">
                <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Announcement Text</label>
                <textarea 
                  className="w-full p-4 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-brand-500 outline-none"
                  value={settings.announcement}
                  onChange={(e) => updateSettings('announcement', e.target.value)}
                  rows={3}
                />
              </div>
            )}
          </div>
        </div>

        {/* Website Identity */}
        <div className="lg:col-span-2 bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
           <div className="p-6 border-b border-gray-100 bg-gray-50 flex items-center gap-3">
             <Smartphone className="text-brand-600" />
             <h3 className="text-xl font-bold text-gray-900">Website Identity</h3>
           </div>
           <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2">Website Title</label>
                  <input 
                    type="text"
                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-500 outline-none font-bold"
                    value={settings.websiteTitle}
                    onChange={(e) => updateSettings('websiteTitle', e.target.value)}
                  />
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-bold text-gray-700 mb-2">Logo</label>
                    <div className="flex items-center gap-3">
                      <div className="w-12 h-12 rounded-xl border border-gray-200 bg-white flex items-center justify-center overflow-hidden shrink-0">
                        {settings.websiteLogo ? <img src={settings.websiteLogo} className="w-full h-full object-contain" /> : <ImageIcon className="text-gray-300" size={20} />}
                      </div>
                      <Button onClick={() => logoInputRef.current?.click()} variant="outline" size="sm" className="text-xs px-2 py-1">
                        {isUploadingLogo ? '...' : 'Upload Logo'}
                      </Button>
                      <input type="file" ref={logoInputRef} className="hidden" accept="image/*" onChange={handleLogoUpload} />
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-gray-700 mb-2">Favicon</label>
                    <div className="flex items-center gap-3">
                      <div className="w-12 h-12 rounded-xl border border-gray-200 bg-white flex items-center justify-center overflow-hidden shrink-0">
                        {settings.websiteFavicon ? <img src={settings.websiteFavicon} className="w-8 h-8 object-contain" /> : <ImageIcon className="text-gray-300" size={20} />}
                      </div>
                      <Button onClick={() => faviconInputRef.current?.click()} variant="outline" size="sm" className="text-xs px-2 py-1">
                        {isUploadingFavicon ? '...' : 'Upload Favicon'}
                      </Button>
                      <input type="file" ref={faviconInputRef} className="hidden" accept="image/*" onChange={handleFaviconUpload} />
                    </div>
                  </div>
                </div>
              </div>

              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2">Contact Email</label>
                  <input 
                    type="email"
                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-500 outline-none"
                    value={settings.contactEmail}
                    onChange={(e) => updateSettings('contactEmail', e.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-2">Contact Phone</label>
                  <input 
                    type="text"
                    className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-500 outline-none"
                    value={settings.contactPhone}
                    onChange={(e) => updateSettings('contactPhone', e.target.value)}
                  />
                </div>
              </div>
              
              <div className="md:col-span-2">
                <label className="block text-sm font-bold text-gray-700 mb-2">Office Address</label>
                <textarea 
                  className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-500 outline-none"
                  value={settings.address}
                  onChange={(e) => updateSettings('address', e.target.value)}
                  rows={2}
                />
              </div>
           </div>
        </div>
      </div>

      {/* 4. Database Setup & SQL */}
      <div className="bg-slate-900 rounded-3xl shadow-2xl overflow-hidden border border-slate-800">
         <div className="p-8 border-b border-slate-800 flex flex-col md:flex-row justify-between items-center gap-6 bg-slate-950">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-blue-500/20 text-blue-400 rounded-2xl"><Database size={32} /></div>
              <div>
                <h3 className="text-2xl font-bold text-white">Database & SQL Configuration</h3>
                <p className="text-slate-400 text-sm">Configure Supabase for global real-time data synchronization</p>
              </div>
            </div>
            {!isSupabaseConfigured && (
              <div className="flex gap-3">
                 <Button onClick={() => handleSaveDbConfig()} disabled={isSaving} className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-xl font-bold shadow-lg shadow-blue-900/50">
                   {isSaving ? 'Connecting...' : 'Connect Supabase'}
                 </Button>
              </div>
            )}
         </div>

         <div className="p-8">
            {!isSupabaseConfigured ? (
              <div className="max-w-3xl mx-auto space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                   <div>
                     <label className="block text-xs font-bold text-slate-500 uppercase mb-2 ml-1">Supabase URL</label>
                     <input type="text" value={dbUrl} onChange={e => setDbUrl(e.target.value)} className="w-full p-4 bg-slate-800 border border-slate-700 rounded-xl text-white outline-none focus:ring-2 focus:ring-blue-500" placeholder="https://xyz.supabase.co" />
                   </div>
                   <div>
                     <label className="block text-xs font-bold text-slate-500 uppercase mb-2 ml-1">Anon Public Key</label>
                     <input type="password" value={dbKey} onChange={e => setDbKey(e.target.value)} className="w-full p-4 bg-slate-800 border border-slate-700 rounded-xl text-white outline-none focus:ring-2 focus:ring-blue-500" placeholder="eyJhbG..." />
                   </div>
                </div>
                <div className="bg-blue-500/10 border border-blue-500/20 p-5 rounded-2xl flex items-start gap-4">
                   <Info className="text-blue-400 shrink-0" size={24} />
                   <p className="text-blue-100 text-sm leading-relaxed">
                     Paste your Supabase credentials here to enable global database syncing. Your settings will be saved locally in this browser. To make them permanent for all users, update the <strong>HARDCODED_URL</strong> in <code className="bg-black/50 px-1 rounded">supabaseClient.ts</code>.
                   </p>
                </div>
              </div>
            ) : (
              <div className="space-y-6">
                 <div className="flex justify-between items-center text-slate-400 text-sm mb-2">
                    <span className="flex items-center gap-2"><CheckCircle size={16} className="text-emerald-500"/> Supabase Connected</span>
                    <button onClick={() => { localStorage.removeItem('dream_sb_url'); localStorage.removeItem('dream_sb_key'); window.location.reload(); }} className="hover:text-red-400 flex items-center gap-1 font-bold text-xs"><RotateCcw size={12}/> Reset Config</button>
                 </div>
                 <div className="relative group">
                    <div className="bg-black/50 rounded-2xl border border-slate-800 p-6 font-mono text-xs text-emerald-400 h-[350px] overflow-y-auto custom-scrollbar">
                      {SCHEMA_SQL}
                    </div>
                    <button 
                      onClick={handleCopySQL} 
                      className="absolute top-4 right-4 bg-white hover:bg-emerald-50 text-slate-900 px-4 py-2 rounded-xl text-sm font-bold flex items-center gap-2 shadow-xl transition-all"
                    >
                      {copied ? <Check size={18} /> : <Copy size={18} />}
                      {copied ? 'Copied SQL' : 'Copy SQL Schema'}
                    </button>
                 </div>
                 <p className="text-slate-500 text-center text-xs">Run this SQL in your Supabase SQL Editor to create required tables.</p>
              </div>
            )}
         </div>
      </div>
    </div>
  );
};
