import React, { useState, useEffect, useRef } from 'react';
import { 
  Monitor, Layout, Layers, ToggleLeft, ToggleRight, 
  AlertTriangle, Megaphone, Power, CheckCircle, Smartphone, Database, Server, HardDrive, Copy, Check, Save, RefreshCw, Key,
  Globe, MapPin, Phone, Mail, Upload, X, Image as ImageIcon,
  Zap, PlusCircle, RotateCcw, Wifi, WifiOff
} from 'lucide-react';
import { Button } from '../../ui/Button';
import { useSiteConfig, ToggableModule, LandingSection } from '../../../contexts/SiteConfigContext';
import { isSupabaseConfigured, supabase } from '../../../services/supabaseClient';
import { AppModule } from '../../../types';

const SCHEMA_SQL = `
-- RESET & FIX PERMISSIONS (Run this to fix "Permission Denied" or "RLS" errors)

-- 1. JOBS
create table if not exists public.jobs (id bigint generated by default as identity primary key, created_at timestamp with time zone default timezone('utc'::text, now()) not null);
alter table public.jobs enable row level security;
create policy "Enable all access for all users" on public.jobs for all using (true) with check (true);

-- 2. BLOGS
create table if not exists public.blogs (id bigint generated by default as identity primary key, created_at timestamp with time zone default timezone('utc'::text, now()) not null);
alter table public.blogs enable row level security;
create policy "Enable all access for all users" on public.blogs for all using (true) with check (true);

-- 3. REQUESTS
create table if not exists public.requests (id bigint generated by default as identity primary key, created_at timestamp with time zone default timezone('utc'::text, now()) not null);
alter table public.requests enable row level security;
create policy "Enable all access for all users" on public.requests for all using (true) with check (true);

-- 4. MARKET PRICES
create table if not exists public.market_prices (id bigint generated by default as identity primary key, created_at timestamp with time zone default timezone('utc'::text, now()) not null);
alter table public.market_prices enable row level security;
create policy "Enable all access for all users" on public.market_prices for all using (true) with check (true);

-- 5. USERS
create table if not exists public.users (id text primary key, created_at timestamp with time zone default timezone('utc'::text, now()) not null);
alter table public.users enable row level security;
create policy "Enable all access for all users" on public.users for all using (true) with check (true);

-- ADD COLUMNS IF MISSING
alter table public.jobs add column if not exists title text;
alter table public.jobs add column if not exists company text;
alter table public.jobs add column if not exists status text default 'Active';
alter table public.jobs add column if not exists level text;

-- GRANT PERMISSIONS TO ANON (Public) API
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
`;

export const AdminWebsiteManage = () => {
  const { modules, sections, settings, toggleModule, toggleSection, updateSettings } = useSiteConfig();
  const [copied, setCopied] = useState(false);
  const logoInputRef = useRef<HTMLInputElement>(null);

  // DB Config State
  const [dbUrl, setDbUrl] = useState(localStorage.getItem('dream_sb_url') || '');
  const [dbKey, setDbKey] = useState(localStorage.getItem('dream_sb_key') || '');
  const [isSaving, setIsSaving] = useState(false);
  const [testResult, setTestResult] = useState<string | null>(null);
  const [statusColor, setStatusColor] = useState('gray');

  useEffect(() => {
      if (isSupabaseConfigured) {
          handleTestConnection(true);
      }
  }, []);

  const handleCopySQL = () => {
    navigator.clipboard.writeText(SCHEMA_SQL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveDbConfig = () => {
    setIsSaving(true);
    let finalUrl = dbUrl.trim();
    // Ensure https://
    if (finalUrl && !finalUrl.startsWith('http')) {
        finalUrl = 'https://' + finalUrl;
        setDbUrl(finalUrl);
    }
    // Remove trailing slash
    if (finalUrl.endsWith('/')) {
        finalUrl = finalUrl.slice(0, -1);
    }

    localStorage.setItem('dream_sb_url', finalUrl);
    localStorage.setItem('dream_sb_key', dbKey.trim());
    
    setTimeout(() => {
        setIsSaving(false);
        alert('Configuration Saved! The page will refresh to connect.');
        window.location.reload();
    }, 1000);
  };

  const handleTestConnection = async (silent = false) => {
      if(!silent) setTestResult('Testing Connection...');
      try {
          // Simple count query
          const { count, error } = await supabase.from('jobs').select('*', { count: 'exact', head: true });
          if (error) {
              setTestResult(`Connection Failed: ${error.message}`);
              setStatusColor('red');
          } else {
              setTestResult(`✅ Connected Successfully! Found ${count} jobs in DB.`);
              setStatusColor('green');
          }
      } catch (err: any) {
          setTestResult(`Network/Client Error: ${err.message}`);
          setStatusColor('red');
      }
  };

  const handleTestInsert = async () => {
      setTestResult('Testing Insert...');
      setStatusColor('orange');
      try {
          const testData = {
              title: 'Test Job ' + Date.now(),
              company: 'Test Company',
              status: 'Draft',
              level: 'Entry'
          };
          const { data, error } = await supabase.from('jobs').insert([testData]).select();
          
          if (error) {
              setTestResult(`❌ Insert Failed:\n${JSON.stringify(error, null, 2)}`);
              setStatusColor('red');
          } else {
              setTestResult(`✅ Insert Success! Created ID: ${data?.[0]?.id}. Check 'jobs' table.`);
              setStatusColor('green');
          }
      } catch (err: any) {
          setTestResult(`Crash Error: ${err.message}`);
          setStatusColor('red');
      }
  };

  const handleDisconnect = () => {
      if(confirm('Are you sure? This will clear the API Key and URL.')) {
          localStorage.removeItem('dream_sb_url');
          localStorage.removeItem('dream_sb_key');
          window.location.reload();
      }
  }

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        updateSettings('websiteLogo', reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleRemoveLogo = () => {
    updateSettings('websiteLogo', '');
    if (logoInputRef.current) logoInputRef.current.value = '';
  };

  const ToggleSwitch = ({ label, checked, onChange, color = 'bg-green-500' }: { label: string, checked: boolean, onChange: () => void, color?: string }) => (
    <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl border border-gray-100 hover:border-gray-300 transition-all">
      <span className="font-medium text-gray-900">{label}</span>
      <button 
        onClick={onChange}
        className={`relative w-12 h-6 rounded-full transition-colors duration-300 ${checked ? color : 'bg-gray-300'}`}
      >
        <div className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full shadow-md transform transition-transform duration-300 ${checked ? 'translate-x-6' : 'translate-x-0'}`}></div>
      </button>
    </div>
  );

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* Global Status Banner */}
      <div className={`p-6 rounded-2xl border-2 flex flex-col md:flex-row items-center justify-between gap-4 ${isSupabaseConfigured ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}>
         <div className="flex items-center gap-4">
            <div className={`p-4 rounded-full ${isSupabaseConfigured ? 'bg-green-200 text-green-700' : 'bg-red-200 text-red-700'}`}>
                {isSupabaseConfigured ? <Wifi size={32} /> : <WifiOff size={32} />}
            </div>
            <div>
                <h2 className={`text-2xl font-bold ${isSupabaseConfigured ? 'text-green-900' : 'text-red-900'}`}>
                    {isSupabaseConfigured ? 'System Online (Global)' : 'System Offline (Local Only)'}
                </h2>
                <p className={`${isSupabaseConfigured ? 'text-green-700' : 'text-red-700'}`}>
                    {isSupabaseConfigured 
                        ? 'All users can see the database updates.' 
                        : 'Updates are only visible on this device.'}
                </p>
            </div>
         </div>
         {isSupabaseConfigured && (
             <div className="text-right">
                 <span className="inline-block bg-green-200 text-green-800 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wider mb-1">Status: Operational</span>
                 <p className="text-xs text-green-700">Code Configuration Detected</p>
             </div>
         )}
      </div>

      {/* Database Connection Panel */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
         <div className={`p-6 border-b flex items-center justify-between bg-gray-50`}>
            <div className="flex items-center gap-3">
                <Database size={24} className="text-gray-600" />
                <h3 className="text-lg font-bold text-gray-900">Database Tools</h3>
            </div>
            {isSupabaseConfigured && (
                <button onClick={handleDisconnect} className="flex items-center gap-1 text-xs text-red-600 font-bold hover:bg-red-50 px-3 py-1 rounded-lg transition-colors border border-red-200">
                    <RotateCcw size={12}/> Clear Browser Cache
                </button>
            )}
         </div>
         
         <div className="p-6">
            {!isSupabaseConfigured ? (
                <div className="space-y-4">
                    <div className="bg-blue-50 p-4 rounded-xl border border-blue-100 text-sm text-blue-800 mb-4">
                        <strong>For Global Access:</strong> Add keys to <code>services/supabaseClient.ts</code> (Recommended) or use the form below for this browser only.
                    </div>
                    <div>
                        <label className="block text-sm font-bold text-gray-700 mb-1">Project URL</label>
                        <input 
                            type="text" 
                            value={dbUrl}
                            onChange={(e) => setDbUrl(e.target.value)}
                            placeholder="https://your-project.supabase.co"
                            className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none font-mono text-sm"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-bold text-gray-700 mb-1">API Key (anon)</label>
                        <div className="relative">
                            <input 
                                type="password" 
                                value={dbKey}
                                onChange={(e) => setDbKey(e.target.value)}
                                placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                                className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none pr-10 font-mono text-sm"
                            />
                            <Key size={16} className="absolute right-4 top-4 text-gray-400"/>
                        </div>
                    </div>
                    <button 
                        onClick={handleSaveDbConfig}
                        disabled={isSaving || !dbUrl || !dbKey}
                        className="w-full py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-lg shadow-blue-200 flex items-center justify-center gap-2"
                    >
                        {isSaving ? <RefreshCw className="animate-spin" /> : <Save size={18} />}
                        {isSaving ? 'Connecting...' : 'Connect Locally'}
                    </button>
                </div>
            ) : (
                <div className="text-center py-6">
                    <div className="flex flex-wrap gap-4 justify-center mb-6">
                        <Button onClick={() => handleTestConnection(false)} variant="outline" className="flex items-center gap-2">
                            <Zap size={16} /> Test Connection
                        </Button>
                        <Button onClick={handleTestInsert} className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white shadow-md">
                            <PlusCircle size={16} /> Test Data Insert
                        </Button>
                    </div>
                    
                    {testResult && (
                        <div className={`mb-6 p-4 rounded-xl border text-left text-sm font-mono whitespace-pre-wrap break-all overflow-x-auto ${
                            statusColor === 'green' ? 'bg-green-50 border-green-200 text-green-900' : 
                            statusColor === 'red' ? 'bg-red-50 border-red-200 text-red-900' :
                            'bg-orange-50 border-orange-200 text-orange-900'
                        }`}>
                            <strong>Result:</strong><br/>
                            {testResult}
                        </div>
                    )}

                    <div className="bg-gray-900 text-white p-6 rounded-2xl border border-gray-800 text-left">
                        <h4 className="font-bold text-lg mb-2 flex items-center gap-2 text-green-400"><Server size={20}/> SQL Setup (One-Time)</h4>
                        <p className="text-sm text-gray-300 mb-4 leading-relaxed">
                            Run this in your Supabase SQL Editor to create tables and fix "Permission denied" errors.
                        </p>
                        
                        <div className="bg-black/50 p-4 rounded-xl font-mono text-xs text-green-300 mb-4 h-48 overflow-y-auto border border-gray-700 custom-scrollbar">
                            {SCHEMA_SQL}
                        </div>

                        <button 
                            onClick={handleCopySQL}
                            className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-green-600 hover:bg-green-700 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-green-900/20"
                        >
                            {copied ? <Check size={18} /> : <Copy size={18} />}
                            {copied ? 'SQL Copied!' : 'Copy SQL Code'}
                        </button>
                    </div>
                </div>
            )}
         </div>
      </div>

      {/* General Settings */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="p-6 border-b border-gray-100 flex items-center gap-3 bg-gray-50">
          <div className="p-2 bg-blue-100 text-blue-700 rounded-lg">
            <Globe size={20} />
          </div>
          <div>
            <h3 className="text-lg font-bold text-gray-900">General Information</h3>
            <p className="text-xs text-gray-500">Website branding, logo, and contact details</p>
          </div>
        </div>
        
        <div className="p-6 grid grid-cols-1 lg:grid-cols-3 gap-8">
           <div className="col-span-1">
              <label className="block text-sm font-bold text-gray-700 mb-3">Website Logo</label>
              <div 
                className="border-2 border-dashed border-gray-300 rounded-xl p-6 flex flex-col items-center justify-center min-h-[200px] cursor-pointer hover:bg-gray-50 transition-colors relative group"
                onClick={() => logoInputRef.current?.click()}
              >
                 <input type="file" accept="image/*" className="hidden" ref={logoInputRef} onChange={handleLogoUpload} />
                 {settings.websiteLogo ? (
                   <div className="relative w-full h-full flex flex-col items-center">
                      <img src={settings.websiteLogo} alt="Logo" className="max-h-32 object-contain mb-2" />
                      <button onClick={(e) => { e.stopPropagation(); handleRemoveLogo(); }} className="absolute top-0 right-0 bg-red-500 text-white p-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"><X size={16} /></button>
                      <p className="text-xs text-gray-500 mt-2">Click to change</p>
                   </div>
                 ) : (
                   <div className="text-center">
                      <div className="bg-gray-100 p-3 rounded-full inline-block mb-3"><ImageIcon size={24} className="text-gray-400" /></div>
                      <p className="text-sm font-bold text-gray-600">Upload Logo</p>
                      <p className="text-xs text-gray-400 mt-1">PNG, JPG, SVG (Max 2MB)</p>
                   </div>
                 )}
              </div>
           </div>
           <div className="col-span-1 lg:col-span-2 space-y-5">
              <div>
                 <label className="block text-sm font-bold text-gray-700 mb-2">Website Title</label>
                 <input type="text" value={settings.websiteTitle} onChange={(e) => updateSettings('websiteTitle', e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none" placeholder="e.g. Dream BD" />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                 <div><label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2"><Mail size={16} className="text-gray-400"/> Contact Email</label><input type="text" value={settings.contactEmail} onChange={(e) => updateSettings('contactEmail', e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none" placeholder="info@example.com" /></div>
                 <div><label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2"><Phone size={16} className="text-gray-400"/> Contact Phone</label><input type="text" value={settings.contactPhone} onChange={(e) => updateSettings('contactPhone', e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none" placeholder="+880 1..." /></div>
              </div>
              <div><label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2"><MapPin size={16} className="text-gray-400"/> Address</label><textarea rows={2} value={settings.address} onChange={(e) => updateSettings('address', e.target.value)} className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none resize-none" placeholder="Office Address..." /></div>
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200">
          <div className="p-5 border-b border-gray-100 flex items-center gap-3"><Layers size={20} className="text-blue-600"/><h3 className="font-bold text-gray-900">Header Modules</h3></div>
          <div className="p-6">
             <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <ToggleSwitch label="Amar Bangladesh" checked={modules[AppModule.AMAR_BD]} onChange={() => toggleModule(AppModule.AMAR_BD)} color="bg-blue-600" />
                <ToggleSwitch label="Amar Jela" checked={modules[AppModule.AMAR_JELA]} onChange={() => toggleModule(AppModule.AMAR_JELA)} color="bg-blue-600" />
                <ToggleSwitch label="Bazar Sodai" checked={modules[AppModule.BAZAR_SODAI]} onChange={() => toggleModule(AppModule.BAZAR_SODAI)} color="bg-blue-600" />
                <ToggleSwitch label="Jobs" checked={modules[AppModule.JOB]} onChange={() => toggleModule(AppModule.JOB)} color="bg-blue-600" />
                <ToggleSwitch label="Blog" checked={modules[AppModule.BLOG]} onChange={() => toggleModule(AppModule.BLOG)} color="bg-blue-600" />
                <ToggleSwitch label="Contact" checked={modules[AppModule.CONTACT]} onChange={() => toggleModule(AppModule.CONTACT)} color="bg-blue-600" />
                <div className="sm:col-span-2 mt-4 mb-2"><p className="text-xs font-bold text-gray-500 uppercase tracking-wider">Services Dropdown Items</p></div>
                <ToggleSwitch label="Agriculture" checked={modules[AppModule.AGRI]} onChange={() => toggleModule(AppModule.AGRI)} color="bg-blue-600" />
                <ToggleSwitch label="Health" checked={modules[AppModule.HEALTH]} onChange={() => toggleModule(AppModule.HEALTH)} color="bg-blue-600" />
                <ToggleSwitch label="Education" checked={modules[AppModule.EDU]} onChange={() => toggleModule(AppModule.EDU)} color="bg-blue-600" />
                <ToggleSwitch label="Transport" checked={modules[AppModule.TRANSPORT]} onChange={() => toggleModule(AppModule.TRANSPORT)} color="bg-blue-600" />
                <ToggleSwitch label="Disaster" checked={modules[AppModule.DISASTER]} onChange={() => toggleModule(AppModule.DISASTER)} color="bg-blue-600" />
                <ToggleSwitch label="Fishery" checked={modules[AppModule.FISHERY]} onChange={() => toggleModule(AppModule.FISHERY)} color="bg-blue-600" />
                <ToggleSwitch label="Waste Mgmt" checked={modules[AppModule.WASTE]} onChange={() => toggleModule(AppModule.WASTE)} color="bg-blue-600" />
                <ToggleSwitch label="Crafts" checked={modules[AppModule.CRAFT]} onChange={() => toggleModule(AppModule.CRAFT)} color="bg-blue-600" />
             </div>
          </div>
        </div>
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 h-fit">
          <div className="p-5 border-b border-gray-100 flex items-center gap-3"><Layout size={20} className="text-indigo-600"/><h3 className="font-bold text-gray-900">Landing Page Sections</h3></div>
          <div className="p-6">
             <div className="space-y-4">
                <ToggleSwitch label="Hero Section (Top Banner)" checked={sections.hero} onChange={() => toggleSection('hero')} color="bg-indigo-600" />
                <ToggleSwitch label="About Platform" checked={sections.about} onChange={() => toggleSection('about')} color="bg-indigo-600" />
                <ToggleSwitch label="How it Works" checked={sections.features} onChange={() => toggleSection('features')} color="bg-indigo-600" />
                <ToggleSwitch label="Beautiful Bangladesh Gallery" checked={sections.gallery} onChange={() => toggleSection('gallery')} color="bg-indigo-600" />
                <ToggleSwitch label="Testimonials" checked={sections.testimonials} onChange={() => toggleSection('testimonials')} color="bg-indigo-600" />
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};